services:
  postgres:
    image: postgres:17-alpine
    container_name: my_postgres_wepost
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data_wepost:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis_wepost
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_wepost:/data
    command: redis-server --appendonly yes --save 60 1 --loglevel warning

volumes:
  db_data_wepost:
  redis_data_wepost:
