services:
  postgres:
    image: postgres:17-alpine
    container_name: my_postgres_wepost
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data_wepost:/var/lib/postgresql/data

volumes:
  db_data_wepost:
